In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.metrics import precision_score, recall_score, accuracy_score, f1_score
from sklearn.metrics import confusion_matrix
# from mlxtend.plotting import plot_confusion_matrix

In [2]:
df1=pd.read_csv("Training-Min-Max-SimDataset.csv")

In [3]:
df1

Occupancy  Appliance ID  Sin(time)     Cos(time)  Sin(day)  Cos(day)  \
0              0             1   -0.96593  2.588200e-01 -0.999250  0.038722   
1              1             5    1.00000  6.120000e-17 -0.816540 -0.577290   
2              0             4   -0.50000 -8.660300e-01 -0.263670 -0.964610   
3              1             4    0.25882  9.659300e-01 -0.094537 -0.995520   
4              0             3   -0.70711 -7.071100e-01  0.811540  0.584300   
...          ...           ...        ...           ...       ...       ...   
84091          0             1   -0.86603 -5.000000e-01  0.811540  0.584300   
84092          1             4    0.70711  7.071100e-01 -0.845250 -0.534370   
84093          1             5   -0.96593  2.588200e-01 -0.068802  0.997630   
84094          1             0    0.25882 -9.659300e-01  0.806480 -0.591260   
84095          0             0   -1.00000 -1.840000e-16  0.936880 -0.349650   

       Power consumption  Min-Max-Norm-Pwr  P(t)-P(t-1)  P(t)-P(t+1)  \
0                    100          0.055556            0            0   
1                    685          0.380556         -675         -631   
2                    719          0.399444          206         -629   
3                    771          0.428333          200         -190   
4                      5          0.002778            2           -1   
...                  ...               ...          ...          ...   
84091                100          0.055556          100            0   
84092                740          0.411111         -524          -51   
84093               1181          0.656111           48          501   
84094                  0          0.000000            0            0   
84095                 60          0.033333            0            0   

       Class Label  
0                4  
1                0  
2                4  
3                0  
4                0  
...            ...  
84091            1  
84092            0  
84093            0  
84094            0  
84095            4  

[84096 rows x 11 columns]

In [4]:
x_train=df1.iloc[:,:-1]
y_train=df1.iloc[:,-1:]

In [5]:
len(x_train),len(y_train)

(84096, 84096)

In [ ]:
# import pickle

In [6]:
# Random Forest Model
from sklearn.ensemble import RandomForestClassifier
classifier= RandomForestClassifier(n_estimators= 100, criterion="entropy")
classifier.fit(x_train, y_train)

C:\Users\admin\AppData\Local\Temp\ipykernel_22288\2458475876.py:4: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  classifier.fit(x_train, y_train)


RandomForestClassifier(criterion='entropy')

In [7]:
df2=pd.read_csv("Testing-Min-Max-SimDataset.csv")

In [8]:
df2

Occupancy  Appliance ID  Sin(time)  Cos(time)  Sin(day)  Cos(day)  \
0              1             0    0.50000   -0.86603   0.89198   0.45207   
1              0             1    0.86603   -0.50000  -0.29671  -0.95497   
2              0             1    0.86603    0.50000   0.78030   0.62541   
3              1             4    0.25882   -0.96593   0.92097   0.38963   
4              1             3    0.50000   -0.86603  -0.78565  -0.61867   
...          ...           ...        ...        ...       ...       ...   
21019          1             0    0.50000    0.86603  -0.24702  -0.96901   
21020          0             3    0.96593    0.25882   0.98293  -0.18400   
21021          1             2    0.86603   -0.50000  -0.95623   0.29260   
21022          1             0    0.86603   -0.50000   0.58080   0.81405   
21023          1             1   -0.86603    0.50000  -0.44052  -0.89774   

       Power consumption  Min-Max-Norm-Pwr  P(t)-P(t-1)  P(t)-P(t+1)  \
0                      0          0.000000            0            0   
1                      0          0.000000            0            0   
2                      0          0.000000            0            0   
3                      0          0.000000            0            0   
4                      4          0.002222            0        -1652   
...                  ...               ...          ...          ...   
21019                  0          0.000000            0            0   
21020                  2          0.001111           -3            0   
21021                  1          0.000556         -254           -2   
21022                  0          0.000000            0            0   
21023                100          0.055556            0            0   

       Class Label  
0                0  
1                0  
2                0  
3                0  
4                0  
...            ...  
21019            0  
21020            0  
21021            2  
21022            0  
21023            0  

[21024 rows x 11 columns]

In [9]:
x_test=df2.iloc[:,:-1]
y_test=df2.iloc[:,-1:]

In [10]:
y_pred= classifier.predict(x_test)

In [11]:
#Confusion Matrix - verify accuracy of each class
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[11926     0     0     0     0]
 [    0  1577     0     0     0]
 [    0     0  1536     0     0]
 [    1     0     0  1260     0]
 [    0     2     0     0  4722]]


In [12]:
from sklearn.metrics import classification_report

# print(class_labels)
target_names = ['Class 0', 'Class 1', 'Class 2', 'Class 3', 'Class 4']
print(classification_report(y_test, y_pred, target_names=target_names,digits=3))

              precision    recall  f1-score   support

     Class 0      1.000     1.000     1.000     11926
     Class 1      0.999     1.000     0.999      1577
     Class 2      1.000     1.000     1.000      1536
     Class 3      1.000     0.999     1.000      1261
     Class 4      1.000     1.000     1.000      4724

    accuracy                          1.000     21024
   macro avg      1.000     1.000     1.000     21024
weighted avg      1.000     1.000     1.000     21024



In [ ]:
################################################################################################################################

In [13]:
from sklearn.svm import SVC
classifier1 = SVC(kernel='rbf',random_state=1)
classifier1.fit(x_train, y_train)

C:\Users\admin\anaconda3\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC(random_state=1)

In [14]:
y_pred1= classifier1.predict(x_test)

In [15]:
#Confusion Matrix - verify accuracy of each class
cm = confusion_matrix(y_test, y_pred1)
print(cm)

[[10614     2     0   219  1091]
 [    0  1577     0     0     0]
 [    4     0  1532     0     0]
 [   39     5     0  1154    63]
 [ 3474     5     0   105  1140]]


In [16]:
from sklearn.metrics import classification_report

# print(class_labels)
target_names = ['Class 0', 'Class 1', 'Class 2', 'Class 3', 'Class 4']
print(classification_report(y_test, y_pred1, target_names=target_names,digits=3))

              precision    recall  f1-score   support

     Class 0      0.751     0.890     0.815     11926
     Class 1      0.992     1.000     0.996      1577
     Class 2      1.000     0.997     0.999      1536
     Class 3      0.781     0.915     0.843      1261
     Class 4      0.497     0.241     0.325      4724

    accuracy                          0.762     21024
   macro avg      0.804     0.809     0.795     21024
weighted avg      0.732     0.762     0.733     21024



In [ ]:
################################################################################################################################

In [17]:
from sklearn.neighbors import KNeighborsClassifier  
classifier2= KNeighborsClassifier(n_neighbors=5, metric='minkowski', p=2 )  
classifier2.fit(x_train, y_train) 

C:\Users\admin\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


KNeighborsClassifier()

In [18]:
y_pred2= classifier2.predict(x_test)

C:\Users\admin\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


In [19]:
#Confusion Matrix - verify accuracy of each class
cm = confusion_matrix(y_test, y_pred2)
print(cm)

[[10152     0     0   100  1674]
 [    0  1577     0     0     0]
 [    0     0  1536     0     0]
 [   48     0     0  1194    19]
 [ 1624     1     0    51  3048]]


In [20]:
from sklearn.metrics import classification_report

# print(class_labels)
target_names = ['Class 0', 'Class 1', 'Class 2', 'Class 3', 'Class 4']
print(classification_report(y_test, y_pred2, target_names=target_names,digits=3))

              precision    recall  f1-score   support

     Class 0      0.859     0.851     0.855     11926
     Class 1      0.999     1.000     1.000      1577
     Class 2      1.000     1.000     1.000      1536
     Class 3      0.888     0.947     0.916      1261
     Class 4      0.643     0.645     0.644      4724

    accuracy                          0.833     21024
   macro avg      0.878     0.889     0.883     21024
weighted avg      0.833     0.833     0.833     21024



In [ ]:
################################################################################################################################

In [21]:
from sklearn.naive_bayes import GaussianNB  
classifier3 = GaussianNB()  
classifier3.fit(x_train, y_train) 

C:\Users\admin\anaconda3\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


GaussianNB()

In [22]:
y_pred3 = classifier3.predict(x_test)

In [23]:
#Confusion Matrix - verify accuracy of each class
cm = confusion_matrix(y_test, y_pred3)
print(cm)

[[3754  200 6576 1318   78]
 [ 445  506    0  106  520]
 [   0    0 1536    0    0]
 [  96    0    0  944  221]
 [   0    0    0  168 4556]]


In [24]:
from sklearn.metrics import classification_report

# print(class_labels)
target_names = ['Class 0', 'Class 1', 'Class 2', 'Class 3', 'Class 4']
print(classification_report(y_test, y_pred3, target_names=target_names,digits=3))

              precision    recall  f1-score   support

     Class 0      0.874     0.315     0.463     11926
     Class 1      0.717     0.321     0.443      1577
     Class 2      0.189     1.000     0.318      1536
     Class 3      0.372     0.749     0.497      1261
     Class 4      0.848     0.964     0.902      4724

    accuracy                          0.537     21024
   macro avg      0.600     0.670     0.525     21024
weighted avg      0.776     0.537     0.552     21024



In [ ]:
################################################################################################################################

In [25]:
from sklearn.tree import DecisionTreeClassifier
classifier4= DecisionTreeClassifier(criterion='entropy', random_state=0)
classifier4.fit(x_train, y_train)

DecisionTreeClassifier(criterion='entropy', random_state=0)

In [26]:
y_pred4= classifier4.predict(x_test)

In [27]:
#Confusion Matrix - verify accuracy of each class
cm = confusion_matrix(y_test, y_pred4)
print(cm)

[[11924     2     0     0     0]
 [    1  1573     0     0     3]
 [    0     0  1536     0     0]
 [    1     0     0  1259     1]
 [    0     2     0     1  4721]]


In [28]:
from sklearn.metrics import classification_report

# print(class_labels)
target_names = ['Class 0', 'Class 1', 'Class 2', 'Class 3', 'Class 4']
print(classification_report(y_test, y_pred4, target_names=target_names,digits=3))

              precision    recall  f1-score   support

     Class 0      1.000     1.000     1.000     11926
     Class 1      0.997     0.997     0.997      1577
     Class 2      1.000     1.000     1.000      1536
     Class 3      0.999     0.998     0.999      1261
     Class 4      0.999     0.999     0.999      4724

    accuracy                          0.999     21024
   macro avg      0.999     0.999     0.999     21024
weighted avg      0.999     0.999     0.999     21024



In [ ]:
################################################################################################################################