In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.metrics import precision_score, recall_score, accuracy_score, f1_score
from sklearn.metrics import confusion_matrix
# from mlxtend.plotting import plot_confusion_matrix

In [2]:
df1=pd.read_csv("Binary-Training-App-Norm-NewSimDataset.csv")

In [3]:
df1

Occupancy  Appliance ID  Sin(time)     Cos(time)  Sin(day)  Cos(day)  \
0              0             1   -0.96593  2.588200e-01 -0.999250  0.038722   
1              1             5    1.00000  6.120000e-17 -0.816540 -0.577290   
2              0             4   -0.50000 -8.660300e-01 -0.263670 -0.964610   
3              1             4    0.25882  9.659300e-01 -0.094537 -0.995520   
4              0             3   -0.70711 -7.071100e-01  0.811540  0.584300   
...          ...           ...        ...           ...       ...       ...   
84091          0             1   -0.86603 -5.000000e-01  0.811540  0.584300   
84092          1             4    0.70711  7.071100e-01 -0.845250 -0.534370   
84093          1             5   -0.96593  2.588200e-01 -0.068802  0.997630   
84094          1             0    0.25882 -9.659300e-01  0.806480 -0.591260   
84095          0             0   -1.00000 -1.840000e-16  0.936880 -0.349650   

       Power consumption  App_norm  P(t)-P(t-1)  P(t)-P(t+1)  Class Label  
0                    100  1.000000            0            0            1  
1                    685  0.456667         -675         -631            0  
2                    719  0.479333          206         -629            1  
3                    771  0.514000          200         -190            0  
4                      5  0.001669            2           -1            0  
...                  ...       ...          ...          ...          ...  
84091                100  1.000000          100            0            0  
84092                740  0.493333         -524          -51            0  
84093               1181  0.787333           48          501            0  
84094                  0  0.000000            0            0            0  
84095                 60  1.000000            0            0            1  

[84096 rows x 11 columns]

In [4]:
x_train=df1.iloc[:,:-1]
y_train=df1.iloc[:,-1:]

In [5]:
len(x_train),len(y_train)

(84096, 84096)

In [ ]:
# import pickle

In [6]:
# Random Forest Model
from sklearn.ensemble import RandomForestClassifier
classifier= RandomForestClassifier(n_estimators= 100, criterion="entropy")
classifier.fit(x_train, y_train)

C:\Users\admin\AppData\Local\Temp\ipykernel_26656\2458475876.py:4: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  classifier.fit(x_train, y_train)


RandomForestClassifier(criterion='entropy')

In [7]:
df2=pd.read_csv("Binary-Testing-App-Norm-NewSimDataset.csv")

In [8]:
df2

Occupancy  Appliance ID  Sin(time)  Cos(time)  Sin(day)  Cos(day)  \
0              1             0    0.50000   -0.86603   0.89198   0.45207   
1              0             1    0.86603   -0.50000  -0.29671  -0.95497   
2              0             1    0.86603    0.50000   0.78030   0.62541   
3              1             4    0.25882   -0.96593   0.92097   0.38963   
4              1             3    0.50000   -0.86603  -0.78565  -0.61867   
...          ...           ...        ...        ...       ...       ...   
21019          1             0    0.50000    0.86603  -0.24702  -0.96901   
21020          0             3    0.96593    0.25882   0.98293  -0.18400   
21021          1             2    0.86603   -0.50000  -0.95623   0.29260   
21022          1             0    0.86603   -0.50000   0.58080   0.81405   
21023          1             1   -0.86603    0.50000  -0.44052  -0.89774   

       Power consumption  App_norm  P(t)-P(t-1)  P(t)-P(t+1)  Class Label  
0                      0  0.000000            0            0            0  
1                      0  0.000000            0            0            0  
2                      0  0.000000            0            0            0  
3                      0  0.000000            0            0            0  
4                      4  0.001112            0        -1652            0  
...                  ...       ...          ...          ...          ...  
21019                  0  0.000000            0            0            0  
21020                  2  0.000000           -3            0            0  
21021                  1  0.000000         -254           -2            0  
21022                  0  0.000000            0            0            0  
21023                100  1.000000            0            0            0  

[21024 rows x 11 columns]

In [9]:
x_test=df2.iloc[:,:-1]
y_test=df2.iloc[:,-1:]

In [10]:
y_pred= classifier.predict(x_test)

In [11]:
#Confusion Matrix - verify accuracy of each class
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[15037     2]
 [    1  5984]]


In [12]:
from sklearn.metrics import classification_report

# print(class_labels)
target_names = ['Class 0', 'Class 1']
print(classification_report(y_test, y_pred, target_names=target_names,digits=3))

              precision    recall  f1-score   support

     Class 0      1.000     1.000     1.000     15039
     Class 1      1.000     1.000     1.000      5985

    accuracy                          1.000     21024
   macro avg      1.000     1.000     1.000     21024
weighted avg      1.000     1.000     1.000     21024



In [ ]:
################################################################################################################################

In [13]:
from sklearn.svm import SVC
classifier1 = SVC(kernel='rbf',random_state=1)
classifier1.fit(x_train, y_train)

C:\Users\admin\anaconda3\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC(random_state=1)

In [14]:
y_pred1= classifier1.predict(x_test)

In [15]:
#Confusion Matrix - verify accuracy of each class
cm = confusion_matrix(y_test, y_pred1)
print(cm)

[[13357  1682]
 [ 3124  2861]]


In [16]:
from sklearn.metrics import classification_report

# print(class_labels)
target_names = ['Class 0', 'Class 1']
print(classification_report(y_test, y_pred1, target_names=target_names,digits=3))

              precision    recall  f1-score   support

     Class 0      0.810     0.888     0.848     15039
     Class 1      0.630     0.478     0.544      5985

    accuracy                          0.771     21024
   macro avg      0.720     0.683     0.696     21024
weighted avg      0.759     0.771     0.761     21024



In [ ]:
################################################################################################################################

In [17]:
from sklearn.neighbors import KNeighborsClassifier  
classifier2= KNeighborsClassifier(n_neighbors=5, metric='minkowski', p=2 )  
classifier2.fit(x_train, y_train) 

C:\Users\admin\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


KNeighborsClassifier()

In [18]:
y_pred2= classifier2.predict(x_test)

C:\Users\admin\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


In [19]:
#Confusion Matrix - verify accuracy of each class
cm = confusion_matrix(y_test, y_pred2)
print(cm)

[[13229  1810]
 [ 1621  4364]]


In [20]:
from sklearn.metrics import classification_report

# print(class_labels)
target_names = ['Class 0', 'Class 1']
print(classification_report(y_test, y_pred2, target_names=target_names,digits=3))

              precision    recall  f1-score   support

     Class 0      0.891     0.880     0.885     15039
     Class 1      0.707     0.729     0.718      5985

    accuracy                          0.837     21024
   macro avg      0.799     0.804     0.802     21024
weighted avg      0.838     0.837     0.838     21024



In [ ]:
################################################################################################################################

In [21]:
from sklearn.naive_bayes import GaussianNB  
classifier3 = GaussianNB()  
classifier3.fit(x_train, y_train) 

C:\Users\admin\anaconda3\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


GaussianNB()

In [22]:
y_pred3 = classifier3.predict(x_test)

In [23]:
#Confusion Matrix - verify accuracy of each class
cm = confusion_matrix(y_test, y_pred3)
print(cm)

[[14127   912]
 [ 1062  4923]]


In [24]:
from sklearn.metrics import classification_report

# print(class_labels)
target_names = ['Class 0', 'Class 1']
print(classification_report(y_test, y_pred3, target_names=target_names,digits=3))

              precision    recall  f1-score   support

     Class 0      0.930     0.939     0.935     15039
     Class 1      0.844     0.823     0.833      5985

    accuracy                          0.906     21024
   macro avg      0.887     0.881     0.884     21024
weighted avg      0.905     0.906     0.906     21024



In [ ]:
################################################################################################################################

In [25]:
from sklearn.tree import DecisionTreeClassifier
classifier4= DecisionTreeClassifier(criterion='entropy', random_state=0)
classifier4.fit(x_train, y_train)

DecisionTreeClassifier(criterion='entropy', random_state=0)

In [26]:
y_pred4= classifier4.predict(x_test)

In [27]:
#Confusion Matrix - verify accuracy of each class
cm = confusion_matrix(y_test, y_pred4)
print(cm)

[[15037     2]
 [    2  5983]]


In [28]:
from sklearn.metrics import classification_report

# print(class_labels)
target_names = ['Class 0', 'Class 1']
print(classification_report(y_test, y_pred4, target_names=target_names,digits=3))

              precision    recall  f1-score   support

     Class 0      1.000     1.000     1.000     15039
     Class 1      1.000     1.000     1.000      5985

    accuracy                          1.000     21024
   macro avg      1.000     1.000     1.000     21024
weighted avg      1.000     1.000     1.000     21024



In [ ]:
################################################################################################################################